### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [fuzz-productions/CoreDataDandy#2]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by nononoah** [comment]
I actually took a stab at it back in July, but was unsatisfied with some of the decisions I made. Ultimately, it's not just Swift 3 that must be supported, but we should also take advantage of the new features Apple has added to Core Data.

Thanks for your interest. I'll be looking into this over the weekend.

**Comment by lfarah** [comment]
Cool! 🎉

**Comment by nononoah** [comment]
Swift 3 is now supported on the master branch and tests are all passing. I'll be checking to make sure Pods and Carthage still deliver the project as expected.

Thanks for bringing this to my attention! 👍

**Comment by lfarah** [comment]
Thanks @nononoah, you're awesome! 🎉
